import { TechnologyRecord } from '../../shared/types/atlas.types.ts';

export const VERIFIED_LOCAL_KNOWLEDGE: TechnologyRecord[] = [
  {
    id: 'tech-bullmq',
    name: 'BullMQ',
    category: 'queue_background',
    description: 'Sistema de colas de mensajes y trabajos en segundo plano ultrarrápido y robusto para Node.js y TypeScript, basado en Redis.',
    howItWorks: 'Utiliza estructuras de datos de Redis (Streams, Hashes, Sorted Sets) con scripts de Lua atómicos para garantizar entrega de mensajes, bloqueos distribuidos (locks) y planificación temporal.',
    problemSolved: 'Procesamiento asíncrono diferido de tareas pesadas (envío de correos, transcodificación, sincronización) sin bloquear el hilo principal de Node.js.',
    prerequisites: ['Node.js 18+', 'Instancia de Redis 6.2+ con soporte para Streams'],
    limitations: ['Requiere mantener y escalar Redis', 'Solo disponible nativamente en el ecosistema Node/TypeScript', 'Consumo de memoria dependiente de retención de trabajos'],
    alternatives: ['RabbitMQ', 'Kafka', 'Temporal', 'Celery (Python)', 'pg-boss (PostgreSQL)'],
    whenToUse: 'Cuando ya utilizas Node.js y Redis y necesitas colas fiables con reintentos exponenciales, tareas programadas (cron) y concurrencia controlada.',
    ecosystem: ['Node.js', 'TypeScript', 'Redis'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-bullmq-1',
        title: 'Documentación Oficial de BullMQ',
        url: 'https://docs.bullmq.io/',
        type: 'official_doc',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
  {
    id: 'tech-temporal',
    name: 'Temporal',
    category: 'queue_background',
    description: 'Motor de orquestación de código como flujos de trabajo (Workflows as Code) con tolerancia a fallos y ejecución duradera.',
    howItWorks: 'Registra el historial de eventos en un servidor central. Si un worker se cae o reinicia, reconstruye el estado exacto mediante replay determinista.',
    problemSolved: 'Flujos de trabajo complejos de larga duración que involucran múltiples microservicios, pagos, rollbacks (Sagas) y pasos humanos diferidos.',
    prerequisites: ['Temporal Cluster (autohospedado o Temporal Cloud)', 'PostgreSQL o Cassandra para persistencia del cluster'],
    limitations: ['Curva de aprendizaje elevada', 'Restricciones estrictas de determinismo en el código de workflows', 'Sobrecarga de infraestructura'],
    alternatives: ['Cadence', 'AWS Step Functions', 'Camunda Zeebe', 'BullMQ'],
    whenToUse: 'Cuando un fallo a mitad de un proceso de múltiples pasos con dinero o datos críticos puede dejar el sistema inconsistente y necesitas compensación automática.',
    ecosystem: ['TypeScript', 'Go', 'Python', 'Java', 'Rust'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-temporal-1',
        title: 'Temporal Official Docs',
        url: 'https://docs.temporal.io/',
        type: 'official_doc',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
  {
    id: 'tech-duckdb',
    name: 'DuckDB',
    category: 'storage_database',
    description: 'Motor de base de datos analítica (OLAP) relacional embebido, orientado a columnas y sin servidor externo.',
    howItWorks: 'Ejecuta consultas vectorizadas sobre columnas en memoria o archivos locales Parquet/CSV/Arrow sin necesidad de configurar un demonio de servidor.',
    problemSolved: 'Análisis de datos a gran escala, agregaciones pesadas y consultas SQL complejas en clientes locales o microservicios sin la complejidad de ClickHouse o Snowflake.',
    prerequisites: ['Compilador C++ o bindings del lenguaje anfitrión (Python, Node, Rust, WASM)'],
    limitations: ['No está diseñado para alta concurrencia de escrituras transaccionales (OLTP)', 'Bloqueo exclusivo en escrituras'],
    alternatives: ['ClickHouse', 'SQLite', 'Polars', 'Apache Arrow'],
    whenToUse: 'Para aplicaciones de escritorio o procesos analíticos que necesitan procesar millones de filas de datos locales en segundos mediante SQL estándar.',
    ecosystem: ['Python', 'Node.js', 'Rust', 'C++', 'Wasm'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-duckdb-1',
        title: 'DuckDB Documentation',
        url: 'https://duckdb.org/docs/',
        type: 'official_doc',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
  {
    id: 'tech-sqlite',
    name: 'SQLite',
    category: 'storage_database',
    description: 'Motor de base de datos relacional transaccional (ACID) embebido, autónomo y con almacenamiento en un único archivo.',
    howItWorks: 'La biblioteca se compila directamente en la aplicación. Lee y escribe directamente en archivos del sistema operativo mediante llamadas POSIX/Win32.',
    problemSolved: 'Persistencia local fiable sin necesidad de instalar, configurar ni administrar un servidor de base de datos como Postgres o MySQL.',
    prerequisites: ['Sistema de archivos accesible con soporte de bloqueos'],
    limitations: ['Un solo escritor simultáneo (modo WAL mitiga la contención lectura/escritura)', 'No diseñado para clústeres distribuidos'],
    alternatives: ['PostgreSQL', 'DuckDB (para analítica)', 'RocksDB (para clave-valor)'],
    whenToUse: 'Aplicaciones de escritorio, herramientas CLI, almacenamiento local en dispositivos móviles y sistemas web de tráfico moderado a alto.',
    ecosystem: ['Universal (C, Rust, Go, Python, Node.js, C#, etc.)'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-sqlite-1',
        title: 'SQLite Official Documentation',
        url: 'https://www.sqlite.org/docs.html',
        type: 'official_doc',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
  {
    id: 'tech-meilisearch',
    name: 'Meilisearch',
    category: 'storage_database',
    description: 'Motor de búsqueda de texto completo ultrarrápido, tolerante a fallos tipográficos y con resultados instantáneos (search-as-you-type).',
    howItWorks: 'Construye índices invertidos basados en LMDB en disco con cálculo de distancia tipográfica y ordenación por relevancia configurable.',
    problemSolved: 'Búsquedas predictivas interactivas en catálogos, documentación y aplicaciones con latencias menores a 50ms sin la pesadez de Elasticsearch.',
    prerequisites: ['Binario de Meilisearch ejecutándose o contenedor Docker'],
    limitations: ['No optimizado para búsquedas de miles de millones de documentos o analítica profunda de logs', 'Consumo significativo de RAM para índices masivos'],
    alternatives: ['Elasticsearch', 'Typesense', 'PostgreSQL full-text search', 'SQLite FTS5'],
    whenToUse: 'Búsquedas en comercio electrónico, plataformas de contenido o documentación técnica que requieren tolerancia a erratas de usuario.',
    ecosystem: ['Rust', 'REST API', 'SDKs en JS/TS, Python, Go, PHP, Ruby'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-meili-1',
        title: 'Meilisearch Documentation',
        url: 'https://www.meilisearch.com/docs',
        type: 'official_doc',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
  {
    id: 'tech-grpc',
    name: 'gRPC',
    category: 'protocol_standard',
    description: 'Framework de llamadas a procedimientos remotos (RPC) de alto rendimiento basado en Protocol Buffers y HTTP/2.',
    howItWorks: 'Define interfaces y mensajes en archivos `.proto`. Genera clientes y servidores con tipado estricto que serializan binarios compactos con multiplexación HTTP/2.',
    problemSolved: 'Comunicación entre microservicios con baja latencia, contratos estrictos fuertemente tipados y streaming bidireccional.',
    prerequisites: ['Compilador protoc o generador de código de lenguaje'],
    limitations: ['No legible directamente por humanos en texto plano', 'Requiere proxy (ej. gRPC-Web o Envoy) para navegadores web estándar'],
    alternatives: ['REST / JSON', 'GraphQL', 'tRPC', 'Connect RPC'],
    whenToUse: 'Sistemas distribuidos de microservicios, streaming continuo de datos o comunicación backend-to-backend de alto rendimiento.',
    ecosystem: ['Go', 'Rust', 'Java', 'Node.js', 'Python', 'C++'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-grpc-1',
        title: 'gRPC Official Documentation',
        url: 'https://grpc.io/docs/',
        type: 'official_doc',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
  {
    id: 'tech-clean-arch',
    name: 'Clean Architecture (Puertos y Adaptadores)',
    category: 'architecture_pattern',
    description: 'Patrón arquitectónico que aísla las reglas de negocio y entidades del dominio de frameworks, bases de datos y detalles de infraestructura.',
    howItWorks: 'Regla de dependencia concéntrica: las capas internas (Dominio, Casos de Uso) nunca conocen las capas externas (HTTP, Base de Datos, UI). Las dependencias se invierten mediante interfaces (puertos) e implementaciones (adaptadores).',
    problemSolved: 'Código acoplado al framework o base de datos que se vuelve imposible de probar de forma unitaria o cambiar de infraestructura sin reescribir la lógica central.',
    prerequisites: ['Comprensión de Inversión de Dependencias (DIP) y diseño guiado por el dominio (DDD)'],
    limitations: ['Mayor cantidad de archivos y capas de abstracción (mappers, DTOs, interfaces)', 'Puede ser sobrediseñado para aplicaciones CRUD simples'],
    alternatives: ['Arquitectura por Capas tradicional', 'Vertical Slice Architecture', 'Microkernel'],
    whenToUse: 'Proyectos de software con reglas de negocio complejas, larga vida útil esperada y necesidad de auditoría y pruebas exhaustivas independientes.',
    ecosystem: ['Agnóstico al lenguaje (TypeScript, Go, Java, C#, Rust, Python)'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-clean-1',
        title: 'The Clean Architecture by Robert C. Martin',
        url: 'https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html',
        type: 'spec_standard',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
  {
    id: 'tech-fastapi',
    name: 'FastAPI',
    category: 'framework',
    description: 'Framework web moderno y de alto rendimiento para construir APIs con Python basado en tipos estándar de Python y Pydantic.',
    howItWorks: 'Usa Starlette para la capa ASGI y Pydantic para validación y serialización de datos con generación automática de esquemas OpenAPI.',
    problemSolved: 'Construcción rápida de APIs en Python con validación automática de datos en tiempo de ejecución y documentación interactiva Swagger.',
    prerequisites: ['Python 3.8+', 'Servidor ASGI como Uvicorn'],
    limitations: ['Rendimiento limitado en comparación con Go o Rust para cargas masivas con saturación de CPU'],
    alternatives: ['Django REST Framework', 'Flask', 'Go Gin/Fiber', 'Express/Fastify'],
    whenToUse: 'Servicios de machine learning, microservicios en Python y APIs REST modernas fuertemente tipadas.',
    ecosystem: ['Python', 'ASGI', 'OpenAPI'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-fastapi-1',
        title: 'FastAPI Official Documentation',
        url: 'https://fastapi.tiangolo.com/',
        type: 'official_doc',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
  {
    id: 'tech-vitest',
    name: 'Vitest',
    category: 'analysis_testing',
    description: 'Framework de pruebas unitarias y de integración ultrarrápido nativo para proyectos basados en Vite y TypeScript.',
    howItWorks: 'Aprovecha la configuración de transformación de Vite y el sistema de módulos ESM nativo con ejecución en hilos de trabajo paralelos.',
    problemSolved: 'Lentitud de arranque y problemas de configuración con TypeScript y ESM en Jest.',
    prerequisites: ['Node.js 18+', 'Vite (opcional pero nativo)'],
    limitations: ['Centrado en el ecosistema Vite/ESM'],
    alternatives: ['Jest', 'Node test runner nativo', 'Mocha'],
    whenToUse: 'Cualquier proyecto frontend o backend en TypeScript con Vite donde la velocidad de iteración y compatibilidad ESM son prioritarias.',
    ecosystem: ['TypeScript', 'JavaScript', 'Vite'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-vitest-1',
        title: 'Vitest Official Documentation',
        url: 'https://vitest.dev/',
        type: 'official_doc',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
  {
    id: 'tech-pgvector',
    name: 'pgvector',
    category: 'storage_database',
    description: 'Extensión de código abierto para PostgreSQL que permite almacenar vectores e indexar búsquedas por similitud semántica.',
    howItWorks: 'Añade el tipo de dato `vector` y los métodos de indexación HNSW e IVFFlat para cálculos de distancia euclidiana, coseno y producto escalar.',
    problemSolved: 'Búsquedas semánticas y Retrieval-Augmented Generation (RAG) en la misma base de datos relacional sin necesidad de desplegar una base vectorial separada.',
    prerequisites: ['PostgreSQL 12+ con permisos de instalación de extensiones'],
    limitations: ['Para conjuntos de más de 50 millones de vectores con altísima frecuencia de escritura, una base dedicada como Qdrant o Milvus puede escalar mejor.'],
    alternatives: ['Qdrant', 'Chroma', 'Pinecone', 'Milvus', 'Weaviate'],
    whenToUse: 'Cuando ya usas PostgreSQL y quieres añadir capacidades de IA y búsqueda semántica conservando transacciones ACID y relaciones relacionales.',
    ecosystem: ['PostgreSQL', 'SQL', 'Python', 'Node.js'],
    maturity: 'stable',
    sources: [
      {
        id: 'src-pgvector-1',
        title: 'pgvector Repository & Docs',
        url: 'https://github.com/pgvector/pgvector',
        type: 'official_doc',
        verifiedAt: '2026-03-01',
      },
    ],
    isVerified: true,
    offlineAvailable: true,
  },
];
